### ISSUE TITLE
New crash related to reddit connection?

### ISSUE THREAD

**Issue by mattabullock** [mattabullock/Baseball-GDT-Bot#15]
```
Traceback (most recent call last):
  File "mets-main.py", line 282, in <module>
    program.run()
  File "mets-main.py", line 269, in run
    sub = r.submit(self.SUBREDDIT, posttitle, edit.generate_code(d,"post"))
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 338, in wrapped
    return function(cls, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 237, in wrapped
    return function(obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 2218, in submit
    retry_on_error=False)
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 163, in wrapped
    return_value = function(reddit_session, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 561, in request_json
    retry_on_error=retry_on_error)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 402, in _request
    response = handle_redirect()
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 375, in handle_redirect
    timeout=timeout, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 144, in wrapped
    result = function(cls, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 54, in wrapped
    return function(cls, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 99, in request
    allow_redirects=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(104, 'Connection reset by     peer'))    
```

**Comment by toddrob99** [comment]
It looks like reddit api was down. I haven't seen this happen, only a graceful error occasionally and then the bot picks up where it left off when the api is working again. If this hasn't happened in 2 years we should close it.
