### ISSUE TITLE
HTTP error when stickying posts (posts still sticky though)

### ISSUE THREAD

**Issue by avery-crudeman** [mattabullock/Baseball-GDT-Bot#16]
Traceback (most recent call last):
  File "maintest.py", line 306, in <module>
    program.run()
  File "maintest.py", line 297, in run
    sub.sticky()
  File "<string>", line 2, in sticky
  File "C:\Python27\lib\site-packages\praw-3.2.1-py2.7.egg\praw\decorators.py",
line 268, in wrap
    return function(_args, *_kwargs)
  File "C:\Python27\lib\site-packages\praw-3.2.1-py2.7.egg\praw\objects.py", lin
e 1378, in sticky
    return self.reddit_session.request_json(url, data=data)
  File "<string>", line 2, in request_json
  File "C:\Python27\lib\site-packages\praw-3.2.1-py2.7.egg\praw\decorators.py",
line 113, in raise_api_exceptions
    return_value = function(_args, *_kwargs)
  File "C:\Python27\lib\site-packages\praw-3.2.1-py2.7.egg\praw__init__.py", li
ne 612, in request_json
    retry_on_error=retry_on_error)
  File "C:\Python27\lib\site-packages\praw-3.2.1-py2.7.egg\praw__init__.py", li
ne 445, in _request
    _raise_response_exceptions(response)
  File "C:\Python27\lib\site-packages\praw-3.2.1-py2.7.egg\praw\internal.py", li
ne 212, in _raise_response_exceptions
    raise HTTPException(_raw=exc.response)
praw.errors.HTTPException: HTTP error

**Comment by toddrob99** [comment]
Just like issue 16 I think this should be closed. I've never seen this happen when stickying posts.
